name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint flake8 black
    - name: Reformat the code with Black
      run: |
        black src
    - name: Analysing the code with Pylint
      run: |
        pylint src
    - name: Analysing the code with Flake8
      run: |
        flake8 src
